CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE ,
    username VARCHAR(20) NOT NULL UNIQUE ,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_of_birth DATE NOT NULL ,
    CONSTRAINT check_users_username_length CHECK ( char_length(username) BETWEEN 8 AND 20)

);