CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL UNIQUE,
    product_description VARCHAR(255),
    product_quantity INTEGER NOT NULL DEFAULT 0,
    product_price NUMERIC(12, 2) NOT NULL,

    CONSTRAINT chk_product_stock CHECK (product_quantity >= 0),

    CONSTRAINT chk_product_price CHECK (product_price >= 0)
);