CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    quantity INTEGER NOT NULL DEFAULT 0,
    price NUMERIC(12, 2) NOT NULL,

    CONSTRAINT chk_stock CHECK (quantity >= 0),

    CONSTRAINT chk_price CHECK (price >= 0)
);