CREATE TABLE  orders(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    customer_id BIGINT NOT NULL ,
    status VARCHAR(50) NOT NULL ,
    order_total_amount NUMERIC(12,2) NOT NULL ,

    FOREIGN KEY (customer_id)
                    REFERENCES users(id)


)