CREATE TABLE order_items(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL ,
    product_id BIGINT NOT NULL ,
    quantity INTEGER NOT NULL DEFAULT 0,
    unit_price NUMERIC(12,2) NOT NULL ,

    CONSTRAINT fk_order_items_order
                        foreign key (order_id)
                        references orders(id),

    CONSTRAINT fk_order_items_product
                        foreign key (product_id)
                        references products(id),

    CONSTRAINT ck_order_items_quantity CHECK ( quantity > 0 ),
    CONSTRAINT ck_order_items_unit_price CHECK ( unit_price >= 0 )

)