CREATE TABLE roles(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(30) NOT NULL
);


CREATE TABLE role_users(
    user_id BIGINT NOT NULL ,
    role_id BIGINT NOT NULL ,


    CONSTRAINT fk_role_users_user
                       FOREIGN KEY (user_id)
                       REFERENCES users(id),

    CONSTRAINT fk_role_users_role
                       FOREIGN KEy (role_id)
                       REFERENCES roles(id)
)