CREATE TABLE refresh_token(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token varchar(150) NOT NULL,
    user_id BIGINT NOT NULL ,
    revoked BOOLEAN DEFAULT FALSE,
    expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_token_user
                          FOREIGN KEY (user_id)
                          REFERENCES users(id)

)




